client_id          = ""
client_secret      = ""
tenant_id          = ""
subscription_id    = ""
attacker_public_ip = "0.0.0.0"
app_id             = "eventgrid_webhook_token"
app_name           = "cumulonimbus"
