client_id          = ""
client_secret      = ""
tenant_id          = ""
subscription_id    = ""
attacker_public_ip = "0.0.0.0"
app_id             = "app_service_env_vars"
app_name           = "cumulonimbus"
