client_id          = ""
client_secret      = ""
tenant_id          = ""
subscription_id    = ""
attacker_public_ip = "0.0.0.0"
app_id             = "container_instance_env"
app_name           = "cumulonimbus"
